server:
  port: 8121
spring:
  application:
    name: dubbo
  dubbo:
    server: true
    application:
      name: consumer
    registry:
      address: zookeeper://173.82.155.113:2181
    protocol:
      name: dubbo
      port: 20880
    scan: com.xxxx.consumer
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bookstore?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true
    username: root
    password: 200011
    jackson:
      date-format: yyyy-MM-dd HH:mm:ss
      time-zone: GMT+8
      serialization:
        write-dates-as-timestamps: false
#  redis:
#    host: 173.82.155.113
#    port: 6379
#    password: 200011
#    database: 0
#    timeout: 10000ms
#    lettuce:
#      pool:
#        max-active: 1024
#        max-wait: 10000ms
#        max-idle: 200
#        min-idle: 5
  rabbitmq:
    host: 173.82.155.113
    port: 5672
    username: dubbo
    password: 200011
    virtual-host: /dubbo
    listener:
      type: simple
      simple:
        prefetch: 1 # 消费者每次从队列获取的消息数量
        concurrency: 20 # 消费者数量
        max-concurrency: 20 # 启动消费者最大数量
        # 重试策略相关配置
        retry:
          enabled: true #开启消费者重试
          max-attempts: 2 #最大重试次数
          initial-interval: 2000 #重试间隔时间
